const employees = [
  {
    id: 101,
    employeeName: "Sai Lakshmi",
    email: "sailakshmi@gmail.com",
    city: "Hyderabad",
    role: "React Developer",
  },
  {
    id: 102,
    employeeName: "Rahul Sharma",
    email: "rahul@gmail.com",
    city: "Bangalore",
    role: "Java Developer",
  },
  {
    id: 103,
    employeeName: "Priya Reddy",
    email: "priya@gmail.com",
    city: "Chennai",
    role: "UI Designer",
  },
  {
    id: 104,
    employeeName: "Kiran Kumar",
    email: "kiran@gmail.com",
    city: "Pune",
    role: "QA Engineer",
  },
  {
    id: 105,
    employeeName: "Anjali Verma",
    email: "anjali@gmail.com",
    city: "Mumbai",
    role: "Full Stack Developer",
  },
  {
    id: 106,
    employeeName: "Ravi Teja",
    email: "ravi@gmail.com",
    city: "Hyderabad",
    role: "Python Developer",
  },
  {
    id: 107,
    employeeName: "Sneha Patel",
    email: "sneha@gmail.com",
    city: "Ahmedabad",
    role: "HR Executive",
  },
  {
    id: 108,
    employeeName: "Arjun Rao",
    email: "arjun@gmail.com",
    city: "Vizag",
    role: "Frontend Developer",
  },
  {
    id: 109,
    employeeName: "Pooja Singh",
    email: "pooja@gmail.com",
    city: "Delhi",
    role: "Business Analyst",
  },
  {
    id: 110,
    employeeName: "Harsha Vardhan",
    email: "harsha@gmail.com",
    city: "Vijayawada",
    role: "Data Analyst",
  },
  {
    id: 111,
    employeeName: "Divya Nair",
    email: "divya@gmail.com",
    city: "Kochi",
    role: "Backend Developer",
  },
  {
    id: 112,
    employeeName: "Nikhil Jain",
    email: "nikhil@gmail.com",
    city: "Jaipur",
    role: "DevOps Engineer",
  },
  {
    id: 113,
    employeeName: "Keerthi Rao",
    email: "keerthi@gmail.com",
    city: "Warangal",
    role: "Software Engineer",
  },
  {
    id: 114,
    employeeName: "Vinay Kumar",
    email: "vinay@gmail.com",
    city: "Mysore",
    role: "Cloud Engineer",
  },
  {
    id: 115,
    employeeName: "Meghana Das",
    email: "meghana@gmail.com",
    city: "Nagpur",
    role: "Project Manager",
  },
  {
    id: 116,
    employeeName: "Ajay Verma",
    email: "ajay@gmail.com",
    city: "Lucknow",
    role: "Technical Support",
  },
  {
    id: 117,
    employeeName: "Sowmya Reddy",
    email: "sowmya@gmail.com",
    city: "Guntur",
    role: "UI Developer",
  },
  {
    id: 118,
    employeeName: "Charan Kumar",
    email: "charan@gmail.com",
    city: "Noida",
    role: "System Administrator",
  },
  {
    id: 119,
    employeeName: "Akhila Devi",
    email: "akhila@gmail.com",
    city: "Bhopal",
    role: "Database Administrator",
  },
  {
    id: 120,
    employeeName: "Sandeep Reddy",
    email: "sandeep@gmail.com",
    city: "Indore",
    role: "AI Engineer",
  }
];

export default employees;